# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fXDFoEWOOA__g2xGC8KeZsC7bcDsFvzp
"""

import numpy as np
import pandas as pd

data = pd.read_csv('excel_utf8.csv', delimiter=';', on_bad_lines='skip')

data.isna().sum()

data = data.dropna()
data = data.drop(["Номер"], axis=1)

data = data[data["Просрочка, дней"].str.contains("-")==False]

data = data[data["Просрочка, дней"].str.contains("#ЗНАЧ!")==False]

data["Просрочка, дней"] = data["Просрочка, дней"].astype("int32")

data["Просрочка, дней"].describe()